
**Assignment 2: Agents and Environments (Given: 31 Jan 2023, Due: 14 Feb 2023 2pm)**
    

**General instructions**

* Solutions are to be typed in the `.ipynb` file provided and uploaded in the lab course page in Moodle before the due date. 
* Your code should be well commented and should be compatible with python3.
* For this assignment, you are allowed to import the libraries `pandas`, `numpy`, `random` and `re` of python3. No other libraries may be imported.

# Text Generation (Static Prediction Task)

(a) Read the text file “speeches.txt” and find the list of unique words with their frequency of occurrence.

In [1]:
import pandas as pd
text_file = open("speeches.txt", encoding="utf8")    #reading the file
words = text_file.read()   #decode('string-escape').decode("utf-8")
words = words.lower()    #Converting all the text to lower alphabets
words = words.split()    
words = [word.strip('.,!;()[]*-') for word in words]    #removing all the characters which aren't words
words = [word.replace("'s", '') for word in words]    #removing 's

unique = []    #creating an empty to store all the unique words
for word in words:
    if word not in unique:    #if word is not already in the list 'unique'
        unique.append(word)

print(unique)    #printing the unique words' list
freq=[0]*len(unique)    #creating an empty list to store the frequencies
for i in range(len(words)):    #for all the words in the original text
    ind = unique.index(words[i])    #finding the index of current word in the list
    freq[ind] += 1   #increasing the value of frequency by 1 at the corresponding index
word_frequency = pd.DataFrame({'Word': unique, 'Frequency': freq})    #making a data frame for printing
print(word_frequency)
print(freq)    #printing the frequency list

['one', 'dollar', 'and', 'eighty-seven', 'cents', 'that', 'was', 'all', 'sixty', 'of', 'it', 'in', 'pennies', 'saved', 'two', 'at', 'a', 'time', 'by', 'bulldozing', 'the', 'grocer', 'vegetable', 'man', 'butcher', 'until', 'cheeks', 'burned', 'with', 'silent', 'imputation', 'parsimony', 'such', 'close', 'dealing', 'implied', 'three', 'times', 'della', 'counted', 'next', 'day', 'would', 'be', 'christmas', 'there', 'clearly', 'nothing', 'left', 'to', 'do', 'but', 'flop', 'down', 'on', 'shabby', 'little', 'couch', 'howl', 'so', 'did', 'which', 'instigates', 'moral', 'reflection', 'life', 'is', 'made', 'up', 'sobs', 'sniffles', 'smiles', 'predominating', 'while', 'mistress', 'home', 'gradually', 'subsiding', 'from', 'first', 'stage', 'second', 'take', 'look', 'furnished', 'flat', '$8', 'per', 'week', 'not', 'exactly', 'beggar', 'description', 'certainly', 'had', 'word', 'look-out', 'for', 'mendicancy', 'squad', 'vestibule', 'below', 'letter-box', 'into', 'no', 'letter', 'go', 'an', 'electri

(b) Let the number of unique words be $n$. Construct an $n \times n$ matrix $M$ where the $i$th row corresponds to the $i$th word, and the $(i, j)$th entry stands for the frequency of occurrence of $j$th word after the $i$th word. Write a function, which accepts a given word, and returns the frequencies of occurrences of the next words (i.e., the row corresponding to the given word).

In [2]:
import numpy as np
def occur(M):
    str = input("Enter the word\n")    #taking the input word
    rind = unique.index(str)    #finding the index of the word
    l = []    #this list will store the row of the corresponding word
    for i in range(unlen):
        l.append(M[rind][i])    #appending the elements to the list
    return l    #returning the required list

unlen = len(unique)    #the number of unique words in the sample
M = np.zeros((unlen, unlen), int)    #creating an empty matrix with the data type int
for i in range(len(words)-1):    #for loop that checks occurence of one word after another
    current_word = words[i]
    next_word = words[i+1]
    current_word_index = unique.index(current_word)    #the indexes of both the words in the unique list
    next_word_index = unique.index(next_word)
    M[current_word_index][next_word_index] += 1    #increasing the value of the matrix by 1
print(M)
occur(M)    #calling the occur function

[[0 3 2 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Enter the word
dollar


[0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


(c) Use $M$ to produce a random text $T$ of length $5000$ where the first word in $T$ is a random word from the input file and the subsequent words are sampled according to $M$.

In [3]:
import numpy as np
from numpy.random import choice
import random

final = []    #this list will store the indexes of the random words generated by the program
string = ""    #this string will store the final words

final.append(random.choice(range(unlen)))    #selecting the first random word
curr = final[0]    #curr will store the current word and will be used to access the row to generate the next word
string += unique[curr] + " "

for i in range(4999):    #the for loop to find the random words
    final.append((choice(range(unlen), 1, p= M[curr]/sum(M[curr])))[0])    #randomly choosing the next word as per the probability of the previous word
    curr=final[i+1]    #updating the curr for the next iteration
    string += unique[final[-1]]    #appending the last element of the index list to the final string
    string += " "

print(string)

egg--but bother the couch and she made my efforts can sell the hardware store stands--'big joe' brady restaurant." "until five blocks soapy proud spirit the vine still talked of a street five baseballs at the meadow plant the moon was a toothpick and care to you recognise it must be properly proclaiming its length now they are only $1.87 with the door bell rang the book on thanksgiving day wore away down to ten," he cried "don't you left?" "well yes for each winter refuge but whenever mr pneumonia to-day there used in new bill of elegant hall bedroom "house heated scrupulously clean conveniences seen a platinum fob chain in his harsh voice he had not in it for long time so seen her tears from the breeze during a daub in store brilliant sparkle still talked of prosperity when his icy cold rain and value–the description but the line that made more comfortable." the twilight they went twirling his pockets and garnered her love and by success would be christmas day dinner and then to their

# Room Cleaning Robot (Dynamic Control Task)

Consider a Room Cleaner Robot which cleans a room containing dirt. A room can be treated as a $m \times n$ grid with walls on all sides. 

(a) Implement an environment which takes as inputs the values $m$ and $n$. Initially, 10 random cells in the grid contain dirt. The list $d_t$ with dimensions $m \times n$ contains the information on the amount of dirt in each cell of the grid. At any point of time, a unit dirt is added at a random location, i.e., a location $(x, y)$ is picked uniformly at random and $d_t(x, y)$ is updated to $d_t(x, y) + 1$.

In [4]:
import random
m = int(input("Enter m : "))    #taking the input of the size of the environment matrix
n = int(input("Enter n : "))
dt = [[0]*n for i in range(m)]    #declaring the empty matrix to save the data of dirt throughout the environment

i = 0
while(1):
    a = random.choice(range(m))    #randomly choosing the coordinates to add dirt
    b = random.choice(range(n))
    if(dt[a][b] == 0):    #if there is no dirt, add 1 unit of dirt
        dt[a][b] = 1
        i += 1
    if(i == 10):    #the loop stops at i=10, i.e. the dirt is present at 10 places
        break

a = random.choice(range(m))    #randomly choosing the coordinates for the new dirt
b = random.choice(range(n))
dt[a][b] += 1   #incrementing the dirt present by 1

print(dt)    #printing the resulting matrix

Enter m : 5
Enter n : 2
[[2, 1], [1, 1], [1, 1], [1, 1], [1, 1]]


(b) Implement an agent which at each time instant $t$ observes its position $o_t =(x_t, y_t)$  (but not the dirt information in this location) and performs a random action $a_t \in \{up,down,right,left, pickDirt\}$. On hitting a wall or picking dirt from the current location $(x_t, y_t)$, the agent stays in the same position $(x_t, y_t)$, otherwise, its position changes according to the action. Every action is associated with a reward (or penalty) defined as follows.

   
$$r_t = R((x_t, y_t), a_t) = 
     \begin{cases}
       -1, &\text{if the agent tries to pick dirt and } (x_t, y_t) \text{ is a clean cell}\\
      -10, &\text{if the agent hits a wall}
       \\ 
       d, &\text{if } (x_t, y_t) \text{ has } d \text{ units of dirt and the agent picks it}\\
       0, &\text{otherwise }
     \end{cases}
$$



In [5]:
import random
def action(r, c, ch, score, m, n, dt):
    print("The coordinates of the robot are " + str(r) + " " + str(c))
    if(ch == 0):    #if the random action is UP
        print("The action is UP")
        r -= 1
        if(r < 0):    #if the agent hits the wall
            score -= 10
            r = 0
    elif(ch == 1):    #if the random action is DOWN
        print("The action is DOWN")
        r += 1
        if(r > m-1):    #if the agent hits the wall
            score -= 10
            r = m-1
    elif(ch == 2):    #if the random action is RIGHT
        print("The action is RIGHT")
        c += 1
        if(c > n-1):    #if the agent hits the wall
            score -= 10
            c = n-1
    elif(ch == 3):    #if the random action is LEFT
        print("The action is LEFT")
        c -= 1
        if(c < 0):    #if the agent hits the wall
            score -= 10
            c = 0
    else:    #if the random action is PICK UP DIRT
        print("The action is PICK UP DIRT")
        if(dt[r][c] > 0):    #if the dirt is present at that location
            score += dt[r][c]     #score increases
            dt[r][c] = 0    #and dirt gets reset
        else:
            score -= 1    #else score gets reduced by 1
    return [r, c, score]    #returning the new coordinates and score

score = 0    #initialising the value of the score at 0

r = random.choice(range(m))    #choosing random initial coordinates of the robot
c = random.choice(range(n))
ch = random.choice(range(5))    #choosing random action, 
new = action(r, c, ch, score, m, n, dt)    #storing the returned list into a temporary list

r = new[0]    #updating to new coordinates
c = new[1]
score = new[2]    #updating the score

print("The score after 1 action is " + str(score))    #printing the score after 1 action
print(dt)    #printing the final matrix

The coordinates of the robot are 2 1
The action is DOWN
The score after 1 action is 0
[[2, 1], [1, 1], [1, 1], [1, 1], [1, 1]]


(c) Print out the activity at each time instant $t$ for $t = 1, \ldots, 1000$. That is, for each $t$, display the grid (with dirt values in each cell), the location of the agent, the action of the agent and the reward obtained. 

In [6]:
import random
for i in range(1000):    #making 1000 actions
    ch = random.choice(range(5))    #choosing random action
    new = action(r, c, ch, score, m, n, dt)    #storing the returned list into a temporary list
    a = random.choice(range(m))    #randomly choosing the coordinates for the new dirt
    b = random.choice(range(n))
    dt[a][b] += 1   #incrementing the dirt present by 1
    r = new[0]    #updating the coordinates and score
    c = new[1]
    score = new[2]
    print("The current score is "+ str(score))    #printing the score and matrix after each action
    print(dt)

The coordinates of the robot are 3 1
The action is DOWN
The current score is 0
[[2, 1], [1, 2], [1, 1], [1, 1], [1, 1]]
The coordinates of the robot are 4 1
The action is UP
The current score is 0
[[2, 1], [1, 2], [1, 1], [2, 1], [1, 1]]
The coordinates of the robot are 3 1
The action is PICK UP DIRT
The current score is 1
[[2, 1], [2, 2], [1, 1], [2, 0], [1, 1]]
The coordinates of the robot are 3 1
The action is UP
The current score is 1
[[2, 1], [2, 2], [1, 1], [3, 0], [1, 1]]
The coordinates of the robot are 2 1
The action is LEFT
The current score is 1
[[2, 1], [2, 2], [1, 1], [3, 1], [1, 1]]
The coordinates of the robot are 2 0
The action is PICK UP DIRT
The current score is 2
[[3, 1], [2, 2], [0, 1], [3, 1], [1, 1]]
The coordinates of the robot are 2 0
The action is DOWN
The current score is 2
[[3, 1], [2, 2], [0, 2], [3, 1], [1, 1]]
The coordinates of the robot are 3 0
The action is DOWN
The current score is 2
[[3, 1], [2, 2], [1, 2], [3, 1], [1, 1]]
The coordinates of the robot

[[3, 5], [3, 0], [18, 1], [24, 15], [14, 28]]
The coordinates of the robot are 1 1
The action is RIGHT
The current score is -1099
[[3, 6], [3, 0], [18, 1], [24, 15], [14, 28]]
The coordinates of the robot are 1 1
The action is LEFT
The current score is -1099
[[3, 6], [3, 0], [18, 1], [24, 15], [14, 29]]
The coordinates of the robot are 1 0
The action is RIGHT
The current score is -1099
[[3, 6], [3, 0], [18, 1], [24, 15], [14, 30]]
The coordinates of the robot are 1 1
The action is DOWN
The current score is -1099
[[3, 6], [3, 0], [18, 1], [24, 15], [15, 30]]
The coordinates of the robot are 2 1
The action is PICK UP DIRT
The current score is -1098
[[3, 7], [3, 0], [18, 0], [24, 15], [15, 30]]
The coordinates of the robot are 2 1
The action is RIGHT
The current score is -1108
[[3, 7], [3, 0], [18, 0], [24, 16], [15, 30]]
The coordinates of the robot are 2 1
The action is LEFT
The current score is -1108
[[3, 7], [3, 0], [18, 0], [24, 16], [16, 30]]
The coordinates of the robot are 2 0
The

# Cricket Match Simulation (Stochastic Control Task)

Consider the following simplified variant of the first innings of a one-day cricket match. The innings consists of 300 balls and at any point of time, treat the pair of batsmen playing as a single player. That is, there are 10 players: $(1, 2),(2, 3), \ldots ,(10, 11)$ with exactly one of them batting. In each ball, there are 5 possible shots $A=\{1, 2, 3, 4, 6\}$ and  each of these shots is associated with a risk of the player getting out. This risk varies from player to player. The probabilities of getting out for Player $(1, 2)$ is $pOutMin = [0.01, 0.02, 0.03, 0.1, 0.3]$ and for Player $(10, 11)$ is $pOutMax = [0.1, 0.2, 0.3, 0.5, 0.7]$,  where the $i$th entry is for the $i$th action. If there are $w$ wickets in hand, then use the formula $pOut(a, w) = pOutMax(a) - (pOutMax(a)-pOutMin(a)) \times (w- 1)/9)$ to calculate the probabilities of getting out for Player $(11-w, 11-w+1)$ where $w \in [10]$. Note that $pOut(a, 1)=pOutMin(a)$ and $pOut(a, 10)=pOutMax(a)$. Taking $pRunMin = 0.5$, and $pRunMax = 0.8$,  when the player is not getting out, the probability of successfully obtaining the runs for that shot is given by $pRun(w) = pRunMin + (pRunMax - pRunMin) \times ((w - 1)/9).$



(a) Implement an environment that maintains the state $s_t = (b_t, w_t)$ where $b_t$ is the balls left and $w_t$ is the wickets left at time $t$. Initialize the start state to $s_1 = (300, 10)$. Write a function that accepts input as $a_t \in A$ and returns $r_t$ (the runs scored on that shot) and $s_t$, and also updates $s_{t+1}$. 

In [7]:
import random
def action(a, s, w):    #defining the action function to choose a random action
    
    Prun = []    #this list will store all the probabilities of the runs scored
    for i in range(5):
        Prun.append(0.5+(0.3*((w-1)/9)))    #using the given relation to find the probabilities
    
    Pmin = [0.01, 0.02, 0.03, 0.1, 0.3]    #saving the Pmin and Pmax
    Pmax = [0.1, 0.2, 0.3, 0.5, 0.7]
    Pout = Pmax[a] - (Pmax[a] - Pmin[a])*((w-1)/9)    #Pout as per the given formula
    
    out = random.choices([0, 1], weights=(Pout, 1 - Pout), k=1)    #randomly choosing if the player is out or not as per the given probability
    ap = random.choices([0, 1], weights=(Prun[a], 1 - Prun[a]), k=1)    #randomly choosing if the player has scored or not as per the given probability

    if(out[0] == 0):    #if the player is out
        w -= 1    #decrease the number of wickets by 1
    else:
        if(ap[0] == 0):    #if the player has scored
            s += runs[a]    #update the score

    return [s, w]    #returning the new runs and wickets as per the outcome

s = 0    #initialising the score to the value 0
w = 10    #giving the initial number of wickets as 10
runs = [1, 2, 3, 4, 6]    #this list will help store the possible values of runs scored in each ball

for i in range(300):    #playing 300 balls of the match
    a = int(input("Enter action : "))    #taking the action as input
    ac = runs.index(a)
    new = action(ac, s, w)    #saving the returned value from the function into a new list
    s = new[0]    #updating the value of new score
    w = new[1]    #updating the value of new wickets
    if(w==0):    #terminating the match if number of wickets left are 0
        break

print("Final score is " + str(s) + " and " + str(w) + " wickets left")    #printing the final result

Enter action : 6
Enter action : 4
Enter action : 6
Enter action : 4
Enter action : 6
Enter action : 4
Final score is 4 and 6 wickets left


(b) Play $a_t = 1$ for each $t$ and find the average balls played and average runs scored by Player $(1,2)$  and Player $(10,11)$.

In [8]:
import random
s = 0    #initialising the score to the value 0
w = 10    #giving the initial number of wickets as 10

avgb = []    #saving the average the number of balls played in this list
avgr = []    #saving the average the number of runs played in this list
balls = 0    #this will store the number of balls played by each of the players
wkt = 0    #this will determine if wicket is taken, to help update the values of balls played
temp = 0    #saving the score of each player in this variable

runs = [1, 2, 3, 4, 6]    #this list will help store the possible values of runs scored in each ball
a = 1    #keeping the action to be 1 Run in each ball
ac = runs.index(a)

for i in range(300):    #playing the game for 300 balls
    if(wkt == 0):    #if wicket is taken
        temp = s    #saving the score of each player after a wicket is taken
        balls = i    #saving the number of balls played by each player after a wicket is taken
        wkt = 1
    
    new = action(ac, s, w)    #calling the function for the outcome of the ball
    if(new[1]<w or i == 299):    #if there is a wicket taken or the match is finished
        wkt = 0    #resetting the value of wkt for next iterations
        avgb.append(i-balls)   #saving the number of balls played
        avgr.append(new[0]-temp)    #saving the number of runs scored

    s = new[0]    #updating the new score and wickets after each ball
    w = new[1]
    if(w==0):    #if there are no wickets left, break the loop
        break

print("Final score is " + str(s) + " and " + str(w) + " wickets left")    #printing the final result
if(w==0):    #if the last player has played
    print("Average runs " + str((avgr[0]+avgr[9])/2) + " and Average balls played " + str(((avgb[0]+avgb[9])/2)+1))    #printing the average runs and balls played
else:
    print("The last player has not played")

Final score is 75 and 0 wickets left
Average runs 10.5 and Average balls played 21.0


(c) Play $a_t=6$ for each $t$ and find the average balls  played and average runs scored by Player $(1,2)$ and Player $(10,11)$.

In [9]:
import random
s = 0    #initialising the score to the value 0
w = 10    #giving the initial number of wickets as 10

avgb = []    #saving the average the number of balls played in this list
avgr = []    #saving the average the number of runs played in this list
balls = 0    #this will store the number of balls played by each of the players
wkt = 0    #this will determine if wicket is taken, to help update the values of balls played
temp = 0    #saving the score of each player in this variable

a = 6    #keeping the action to be 6 Run in each ball
ac = runs.index(a)

for i in range(300):    #playing the game for 300 balls
    if(wkt == 0):    #if wicket is taken
        temp = s    #saving the score of each player after a wicket is taken
        balls = i    #saving the number of balls played by each player after a wicket is taken
        wkt = 1
    
    new = action(ac, s, w)    #calling the function for the outcome of the ball
    if(new[1]<w or i == 299):    #if there is a wicket taken or the match is finished
        wkt = 0    #resetting the value of wkt for next iterations
        avgb.append(i-balls)   #saving the number of balls played
        avgr.append(new[0]-temp)    #saving the number of runs scored

    s = new[0]    #updating the new score and wickets after each ball
    w = new[1]
    if(w==0):    #if there are no wickets left, break the loop
        break

print("Final score is " + str(s) + " and " + str(w) + " wickets left")    #printing the final result
if(w==0):    #if the last player has played
    print("Average runs " + str((avgr[0]+avgr[9])/2) + " and Average balls played " + str(((avgb[0]+avgb[9])/2)+1))    #printing the average runs and balls played
else:
    print("The last player has not played")

Final score is 24 and 0 wickets left
Average runs 0.0 and Average balls played 1.0


(d) Simulate 10 matches, for different constant strategies like $a_t = 1$ for each $t$, $a_t = 2$ for each $t$, etc. and and find the average runs obtained in each of the strategies.

In [26]:
for k in range(5):    #for each different constant strategy
    ans = 0
    for m in range(10):
        s = 0    #initialising the score to the value 0
        w = 10    #giving the initial number of wickets as 10

        avgb = []    #saving the average the number of balls played in this list
        avgr = []    #saving the average the number of runs played in this list
        balls = 0    #this will store the number of balls played by each of the players
        wkt = 0    #this will determine if wicket is taken, to help update the values of balls played
        temp = 0    #saving the score of each player in this variable

        for i in range(300):    #playing the game for 300 balls
            if(wkt == 0):    #if wicket is taken
                temp = s    #saving the score of each player after a wicket is taken
                balls = i    #saving the number of balls played by each player after a wicket is taken
                wkt = 1

            new = action(k, s, w)    #calling the function for the outcome of the ball
            if(new[1]<w or i == 299):    #if there is a wicket taken or the match is finished
                wkt = 0    #resetting the value of wkt for next iterations
                avgb.append(i-balls)   #saving the number of balls played
                avgr.append(new[0]-temp)    #saving the number of runs scored

            s = new[0]    #updating the new score and wickets after each ball
            w = new[1]
            if(w==0):    #if there are no wickets left, break the loop
                break
        ans += s    #adding the final score after each match
    print("The average score for each match is " + str(ans/10) + " for " + str(runs[k]) + " runs in each ball")    #printing the final average after 10 matches

The average score for each match is 188.5 for 1 runs in each ball
The average score for each match is 159.4 for 2 runs in each ball
The average score for each match is 243.9 for 3 runs in each ball
The average score for each match is 114.0 for 4 runs in each ball
The average score for each match is 56.4 for 6 runs in each ball
